### ISSUE TITLE
Ошибка PEP8

### ISSUE THREAD

**Issue by lokidess** [straus123/strais#1]
https://github.com/straus123/strais/blob/78229b495829affea26a22a7b53e4ad2e1d4b2ec/server/server.py#L9

По стандартам написания кода, одноствольные переменные это зло, как я понял из статьи на Пикабу, проект будет расширятся, а код с одностмвольными переменными тяжело поддерживать в будущем

**Comment by straus123** [comment]
Спасибо за замечание, да я буду писать проект по мере сил=)
Исправил:
https://github.com/straus123/strais/pull/4
