### ISSUE TITLE
Упрощение метода read

### ISSUE THREAD

**Issue by lokidess** [straus123/strais#2]
https://github.com/straus123/strais/blob/78229b495829affea26a22a7b53e4ad2e1d4b2ec/server/server.py#L19

В методе целая гора проверок, тесты на такой метод будет писать мучительно больно, да и проверки в основном завязаны на значении переменно action можно сделать три приватных метода и через словарь их гетать, ну или через getattr по маске, что и быстрее будет и красивее в плане кода

**Comment by straus123** [comment]
Отличная идея!
Спасибо!
https://github.com/straus123/strais/pull/5
