### ISSUE TITLE
Настройки приложения

### ISSUE THREAD

**Issue by lokidess** [straus123/strais#3]
https://github.com/straus123/strais/blob/78229b495829affea26a22a7b53e4ad2e1d4b2ec/client/client.py#L4

Для такого рода переменных лучше использовать переменные окружения и в программу передавать их как `HOST = os.getenv("HOST")` или же через конфигурационный файлик типа ini так приложение будет более гибким в настройке

**Comment by straus123** [comment]
Спасибо!
Перенес конфигурацию в .env файлы
https://github.com/straus123/strais/pull/6
